export  const platforms = [
    { id: 1, name: "Linux" },
    { id: 2, name: "Super Nintendo" },
    { id: 3, name: "Nintendo Switch" },
    { id: 4, name: "Wii U" },
    { id: 5, name: "Xbox 360" },
    { id: 6, name: "Xbox One" },
    { id: 7, name: "PlayStation" },
    { id: 8, name: "PlayStation 2" },
    { id: 9, name: "PlayStation 3" },
    { id: 10, name: "PlayStation 4" },
    { id: 11, name: "PlayStation 5" },
    { id: 12, name: "PSP" },
    { id: 13, name: "PS Vita" },
    { id: 14, name: "Android" },
    { id: 15, name: "Web" },
    { id: 16, name: "PC" },
    { id: 17, name: "macOS" },
  ];